[package]
name	= "url-shortener"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket		= "0.5.0"
serde		= "1.0.197"

[dependencies.rocket_sync_db_pools]
version = "0.1.0"
features = ["sqlite_pool"]

[dependencies.rocket_dyn_templates]
version = "0.1.0"
features = ["tera"]
