[package]
name	= "url-shortener"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket		= { version = "0.5.0", features = ["tls"] }
serde		= "1.0.197"

[dependencies.rocket_sync_db_pools]
version = "0.1.0"
features = ["sqlite_pool"]
